// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kypp4xEoplbXz38kjzLwK2JKdiz-Z_o',
    appId: '1:259266095345:web:8dbb60935380a039f86150',
    messagingSenderId: '259266095345',
    projectId: 'do-an-food',
    authDomain: 'do-an-food.firebaseapp.com',
    storageBucket: 'do-an-food.firebasestorage.app',
    measurementId: 'G-5C9CC2PTM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbLkOmsVU6WWPA0zi_MpBQAxHS4UNxzk4',
    appId: '1:259266095345:android:3d40e19e31453eaef86150',
    messagingSenderId: '259266095345',
    projectId: 'do-an-food',
    storageBucket: 'do-an-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnxPeZk9J0vRZGpIg8QBWKN_eAetylY8',
    appId: '1:259266095345:ios:bf359b112d19e0daf86150',
    messagingSenderId: '259266095345',
    projectId: 'do-an-food',
    storageBucket: 'do-an-food.firebasestorage.app',
    iosBundleId: 'com.example.doAnFoodMoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnxPeZk9J0vRZGpIg8QBWKN_eAetylY8',
    appId: '1:259266095345:ios:bf359b112d19e0daf86150',
    messagingSenderId: '259266095345',
    projectId: 'do-an-food',
    storageBucket: 'do-an-food.firebasestorage.app',
    iosBundleId: 'com.example.doAnFoodMoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kypp4xEoplbXz38kjzLwK2JKdiz-Z_o',
    appId: '1:259266095345:web:eca9d7adaf879b60f86150',
    messagingSenderId: '259266095345',
    projectId: 'do-an-food',
    authDomain: 'do-an-food.firebaseapp.com',
    storageBucket: 'do-an-food.firebasestorage.app',
    measurementId: 'G-L0KVYB3JZ7',
  );
}
